trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'azuredevops'
  resourceGroupName: 'azure-devops-rg'
  storageAccountName: 'azuredevopsneerajsa'
  cdnProfileName: 'azure-devops-cdn'
  containerName: 'website'  # this is variable for the container name
  activeEnvironment: 'blue' # Initialize to 'blue' or 'green'

stages:
- stage: 'DeployInfrastructure'
  jobs:
  - job: 'Deploy'
    steps:
    - checkout: self
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment group create --resource-group $(resourceGroupName) --template-file ./azure-static-website/main.bicep --parameters storageAccountName=$(storageAccountName)

- stage: 'DeployWebsite'
  jobs:
  - job: 'DeployWebsite'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az storage container create \
            --name $(containerName) \
            --account-name $(storageAccountName)$(activeEnvironment) \
            --fail-on-exist

          az storage blob upload-batch \
            --destination $(containerName) \
            --source ./azure-static-website/website/ \
            --account-name $(storageAccountName)$(activeEnvironment) 


- stage: 'RunTests'
  jobs:
  - job: 'RunPesterTests'
    steps:
    - powershell: |
        Write-Output "APP_ID: $env:APP_ID"
        Write-Output "SECRET: $env:SECRET"
        Write-Output "TENANT_ID: $env:TENANT_ID"
      displayName: 'Print Environment Variables'

    - checkout: self
    - powershell: Install-Module -Name Pester -Force -SkipPublisherCheck
      displayName: 'Install Pester'
    - powershell: Install-Module -Name Az -AllowClobber -Force -SkipPublisherCheck
      displayName: 'Install Azure PowerShell Module'
    - powershell: |
        $secureSecret = ConvertTo-SecureString -String $env:SECRET -AsPlainText -Force
        $psCredential = New-Object PSCredential -ArgumentList $env:APP_ID, $secureSecret
        Connect-AzAccount -ServicePrincipal -Credential $psCredential -Tenant $env:TENANT_ID
      displayName: 'Connect to Azure Account'   
    - powershell: |
        .\infra-tests\Infrastructure.Test.ps1 -resourceGroupName $(resourceGroupName) -storageAccountName $(storageAccountName) -cdnProfileName $(cdnProfileName)
      displayName: 'Run Pester Tests'
    - powershell: |
        $envToCheck = "$(activeEnvironment)"
        if ($envToCheck -eq 'blue') {
          Write-Host "##vso[task.setvariable variable=activeEnvironment;isOutput=true]green"
        } else {
          Write-Host "##vso[task.setvariable variable=activeEnvironment;isOutput=true]blue"
        }
      displayName: 'Toggle Active Environment'
      name: setvarStep
    - script: echo "Active environment after toggle: $(setvarStep.activeEnvironment)"
