trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'azuredevops'
  resourceGroupName: 'azure-devops-rg'
  storageAccountName: 'azuredevopsneerajsa'
  cdnProfileName: 'azure-devops-cdn'

stages:
- stage: 'DeployInfrastructure'
  jobs:
  - job: 'Deploy'
    steps:
    - checkout: self
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment group create --resource-group $(resourceGroupName) --template-file ./azure-static-website/main.bicep --parameters storageAccountName=$(storageAccountName)

# Add this stage to deploy your static website content
- stage: 'DeployWebsite'
  jobs:
  - job: 'DeployWebsite'
    steps:
    - task: AzureFileCopy@4
      inputs:
        sourcePath: './website'
        azureSubscription: $(azureSubscription)
        destination: 'AzureBlob'
        storage: $(storageAccountName)
        containerName: 'website'

- stage: 'RunTests'
  jobs:
  - job: 'RunPesterTests'
    steps:
    - checkout: self
    - powershell: Install-Module -Name Pester -Force -SkipPublisherCheck
      displayName: 'Install Pester'
    - powershell: |
        .\infra-tests\Infrastructure.Tests.ps1 -resourceGroupName $(resourceGroupName) -storageAccountName $(storageAccountName) -cdnProfileName $(cdnProfileName)
      displayName: 'Run Pester Tests'
